/// Bundled amal catalog — the offline fallback used by guests and whenever
/// /api/amal/definitions is unreachable. Mirrors ALL of
/// packages/content/amal-catalog.json EXACTLY (titles, targets, units, sort
/// order) so a guest diary is the full paper diary, not a subset (it used to
/// carry only the first 15 — no করণীয়-বর্জনীয়, weekly or monthly rows).
/// test/diary_layout_test.dart fails if the two drift apart.
library;

import '../models/amal.dart';
import '../models/user.dart';

/// One fallback amal definition (AmalDefinition-shaped record).
/// `target` is the per-user-category target map ({"general":1,"hafez":…}).
typedef FallbackAmal = ({
  String key,
  String titleBn,
  String titleEn,
  String category,
  String inputType,
  String cadence,
  int sortOrder,
  Map<String, num>? target,
  String? unit,
  String? autoSource,
});

const List<FallbackAmal> kFallbackAmalCatalog = <FallbackAmal>[
  (
    key: 'salat_fajr',
    titleBn: 'ফজর নামাজ',
    titleEn: 'Fajr Prayer',
    category: 'salah',
    inputType: 'tristate',
    cadence: 'daily',
    sortOrder: 10,
    target: null,
    unit: null,
    autoSource: 'auto:prayer:fajr',
  ),
  (
    key: 'salat_dhuhr',
    titleBn: 'যোহর নামাজ',
    titleEn: 'Dhuhr Prayer',
    category: 'salah',
    inputType: 'tristate',
    cadence: 'daily',
    sortOrder: 20,
    target: null,
    unit: null,
    autoSource: 'auto:prayer:dhuhr',
  ),
  (
    key: 'salat_asr',
    titleBn: 'আসর নামাজ',
    titleEn: 'Asr Prayer',
    category: 'salah',
    inputType: 'tristate',
    cadence: 'daily',
    sortOrder: 30,
    target: null,
    unit: null,
    autoSource: 'auto:prayer:asr',
  ),
  (
    key: 'salat_maghrib',
    titleBn: 'মাগরিব নামাজ',
    titleEn: 'Maghrib Prayer',
    category: 'salah',
    inputType: 'tristate',
    cadence: 'daily',
    sortOrder: 40,
    target: null,
    unit: null,
    autoSource: 'auto:prayer:maghrib',
  ),
  (
    key: 'salat_isha',
    titleBn: 'এশা নামাজ',
    titleEn: 'Isha Prayer',
    category: 'salah',
    inputType: 'tristate',
    cadence: 'daily',
    sortOrder: 50,
    target: null,
    unit: null,
    autoSource: 'auto:prayer:isha',
  ),
  (
    key: 'salat_witr',
    titleBn: 'বিতর নামাজ',
    titleEn: 'Witr Prayer',
    category: 'salah',
    inputType: 'boolean',
    cadence: 'daily',
    sortOrder: 60,
    target: null,
    unit: null,
    autoSource: null,
  ),
  (
    key: 'sunnah_muakkadah_12',
    titleBn: '১২ রাকাত সুন্নতে মুয়াক্কাদাহ',
    titleEn: '12 Rak\'ah Sunnah Mu\'akkadah',
    category: 'salah',
    inputType: 'boolean',
    cadence: 'daily',
    sortOrder: 70,
    target: null,
    unit: null,
    autoSource: null,
  ),
  (
    key: 'tahajjud',
    titleBn: 'তাহাজ্জুদ নামাজ',
    titleEn: 'Tahajjud Prayer',
    category: 'salah',
    inputType: 'boolean',
    cadence: 'daily',
    sortOrder: 80,
    target: null,
    unit: null,
    autoSource: null,
  ),
  (
    key: 'ishraq_salat',
    titleBn: 'ইশরাক নামাজ',
    titleEn: 'Ishraq (Duha) Prayer',
    category: 'salah',
    inputType: 'boolean',
    cadence: 'daily',
    sortOrder: 90,
    target: null,
    unit: null,
    autoSource: null,
  ),
  (
    key: 'tilawat',
    titleBn: 'কুরআন তিলাওয়াত',
    titleEn: 'Qur\'an Recitation',
    category: 'quran',
    inputType: 'quantity',
    cadence: 'daily',
    sortOrder: 100,
    target: {'general': 1, 'hafez': 1, 'alim': 10},
    unit: 'পৃষ্ঠা/পারা — হাফেজ: ১ পারা · আলেম: ১০ পৃষ্ঠা · সাধারণ: ১ পৃষ্ঠা',
    autoSource: 'auto:quran:tilawat',
  ),
  (
    key: 'tilawat_minutes',
    titleBn: 'তিলাওয়াত (মিনিট)',
    titleEn: 'Qur\'an Recitation (minutes)',
    category: 'quran',
    inputType: 'quantity',
    cadence: 'daily',
    sortOrder: 105,
    target: {'general': 10, 'hafez': 10, 'alim': 10},
    unit: 'মিনিট — শুরুর পর্যায়ে যারা এখনো পৃষ্ঠা হিসাবে পড়তে পারেন না',
    autoSource: null,
  ),
  (
    key: 'quran_reading',
    titleBn: 'কুরআনের অনুবাদ / ইসলামিক গ্রন্থ পাঠ',
    titleEn: 'Qur\'an Translation / Islamic Reading',
    category: 'quran',
    inputType: 'quantity',
    cadence: 'daily',
    sortOrder: 110,
    target: null,
    unit: 'পৃষ্ঠা',
    autoSource: null,
  ),
  (
    key: 'adhkar_morning',
    titleBn: 'সকালের মাসনূন আযকার (কমপক্ষে ৫ টি)',
    titleEn: 'Morning Adhkar (5 min+)',
    category: 'dhikr',
    inputType: 'boolean',
    cadence: 'daily',
    sortOrder: 120,
    target: null,
    unit: null,
    autoSource: 'auto:adhkar:morning',
  ),
  (
    key: 'adhkar_evening',
    titleBn: 'সন্ধ্যার মাসনূন আযকার (কমপক্ষে ৫ টি)',
    titleEn: 'Evening Adhkar (5 min+)',
    category: 'dhikr',
    inputType: 'boolean',
    cadence: 'daily',
    sortOrder: 130,
    target: null,
    unit: null,
    autoSource: 'auto:adhkar:evening',
  ),
  (
    key: 'post_salat_tasbih',
    titleBn: 'নামাজের পর তাসবীহ ও দোয়া কার্ড',
    titleEn: 'Post-Salah Tasbih & Dua Card',
    category: 'dhikr',
    inputType: 'boolean',
    cadence: 'daily',
    sortOrder: 140,
    target: null,
    unit: null,
    autoSource: 'auto:adhkar:post_salat',
  ),
  (
    key: 'dua_private_10min',
    titleBn: 'কমপক্ষে ১০ মিনিট একান্ত দোয়া/মুনাজাত ও মুহাসাবা',
    titleEn: 'Private Dua & Muhasaba (10 min+)',
    category: 'dhikr',
    inputType: 'boolean',
    cadence: 'daily',
    sortOrder: 150,
    target: null,
    unit: null,
    autoSource: null,
  ),
  (
    key: 'durood_100',
    titleBn: 'দরুদ শরীফ',
    titleEn: 'Durood Sharif',
    category: 'dhikr',
    inputType: 'count',
    cadence: 'daily',
    sortOrder: 160,
    target: {'general': 100, 'hafez': 100, 'alim': 100},
    unit: 'টি',
    autoSource: null,
  ),
  (
    key: 'istighfar_100',
    titleBn: 'ইস্তিগফার',
    titleEn: 'Istighfar',
    category: 'dhikr',
    inputType: 'count',
    cadence: 'daily',
    sortOrder: 170,
    target: {'general': 100, 'hafez': 100, 'alim': 100},
    unit: 'টি',
    autoSource: null,
  ),
  (
    key: 'dhikr_any',
    titleBn: 'যেকোনো যিকর',
    titleEn: 'Any Dhikr',
    category: 'dhikr',
    inputType: 'count',
    cadence: 'daily',
    sortOrder: 180,
    target: null,
    unit: 'টি',
    autoSource: null,
  ),
  (
    key: 'miswak_5',
    titleBn: 'মিসওয়াক',
    titleEn: 'Miswak',
    category: 'dhikr',
    inputType: 'count',
    cadence: 'daily',
    sortOrder: 190,
    target: {'general': 5, 'hafez': 5, 'alim': 5},
    unit: 'টি (৫ বারের মধ্যে)',
    autoSource: null,
  ),
  (
    key: 'muzakara_imani',
    titleBn: 'কমপক্ষে ১টি ঈমানি মুযাকারা (আলাপ)',
    titleEn: 'At Least 1 Imani Discussion (Muzakara)',
    category: 'dawat',
    inputType: 'boolean',
    cadence: 'daily',
    sortOrder: 200,
    target: null,
    unit: null,
    autoSource: null,
  ),
  (
    key: 'help_person',
    titleBn: 'কমপক্ষে ১ জনকে সাহায্য করা',
    titleEn: 'Helping At Least 1 Person',
    category: 'dawat',
    inputType: 'boolean',
    cadence: 'daily',
    sortOrder: 210,
    target: null,
    unit: null,
    autoSource: null,
  ),
  (
    key: 'dawat_15min',
    titleBn: 'কমপক্ষে ১৫ মিনিট দাওয়াতি কাজ',
    titleEn: 'Dawah Work (15 min+)',
    category: 'dawat',
    inputType: 'boolean',
    cadence: 'daily',
    sortOrder: 220,
    target: null,
    unit: null,
    autoSource: null,
  ),
  (
    key: 'salat_slowly',
    titleBn: 'ধীরে-সুস্থে নামাজ (প্রতি রাকাত ২.৫ মিনিট+)',
    titleEn: 'Praying Slowly & With Composure (2.5 min+ per Rak\'ah)',
    category: 'lifestyle',
    inputType: 'boolean',
    cadence: 'daily',
    sortOrder: 230,
    target: null,
    unit: null,
    autoSource: null,
  ),
  (
    key: 'exercise_minutes',
    titleBn: 'শরীরচর্চা / হাঁটা (মিনিট)',
    titleEn: 'Exercise / Walking (minutes)',
    category: 'lifestyle',
    inputType: 'quantity',
    cadence: 'daily',
    sortOrder: 235,
    target: {'general': 20, 'hafez': 20, 'alim': 20},
    unit: 'মিনিট',
    autoSource: null,
  ),
  (
    key: 'avoided_entertainment',
    titleBn: 'হারাম বিনোদন (নাটক/সিনেমা/গান/রিলস) থেকে বেঁচে থাকা',
    titleEn: 'Avoiding Haram Entertainment (Dramas/Movies/Songs/Reels)',
    category: 'lifestyle',
    inputType: 'boolean',
    cadence: 'daily',
    sortOrder: 240,
    target: null,
    unit: null,
    autoSource: null,
  ),
  (
    key: 'bed_by_1030',
    titleBn: 'রাত ১০:৩০-এর মধ্যে ঘুমাতে যাওয়া',
    titleEn: 'Sleeping by 10:30 PM',
    category: 'lifestyle',
    inputType: 'boolean',
    cadence: 'daily',
    sortOrder: 250,
    target: null,
    unit: null,
    autoSource: null,
  ),
  (
    key: 'no_sleep_before_ishraq',
    titleBn: 'ইশরাকের আগে ঘুমাতে না যাওয়া',
    titleEn: 'Not Sleeping Again Before Ishraq',
    category: 'lifestyle',
    inputType: 'boolean',
    cadence: 'daily',
    sortOrder: 260,
    target: null,
    unit: null,
    autoSource: null,
  ),
  (
    key: 'kahf_friday',
    titleBn: 'শুক্রবারে সূরা কাহফ পাঠ',
    titleEn: 'Surah Kahf on Friday',
    category: 'sunnah',
    inputType: 'boolean',
    cadence: 'weekly:fri',
    sortOrder: 270,
    target: null,
    unit: null,
    autoSource: null,
  ),
  (
    key: 'dua_before_maghrib_friday',
    titleBn: 'শুক্রবারে মাগরিবের আগে দোয়া',
    titleEn: 'Dua Before Maghrib on Friday',
    category: 'sunnah',
    inputType: 'boolean',
    cadence: 'weekly:fri',
    sortOrder: 280,
    target: null,
    unit: null,
    autoSource: null,
  ),
  (
    key: 'fast_mon_thu',
    titleBn: 'সোমবার বা বৃহস্পতিবার রোজা',
    titleEn: 'Fasting on Monday or Thursday',
    category: 'sunnah',
    inputType: 'boolean',
    cadence: 'weekly:mon_thu',
    sortOrder: 290,
    target: null,
    unit: null,
    autoSource: null,
  ),
  (
    key: 'check_relative',
    titleBn: 'আত্মীয়ের খোঁজখবর নেওয়া',
    titleEn: 'Keeping in Touch with Relatives',
    category: 'sunnah',
    inputType: 'boolean',
    cadence: 'weekly:any',
    sortOrder: 300,
    target: null,
    unit: null,
    autoSource: null,
  ),
  (
    key: 'ayyam_beez',
    titleBn: 'আইয়ামে বীজ রোজা (১৩–১৫ হিজরি)',
    titleEn: 'Ayyam al-Beed Fasting (13-15 Hijri)',
    category: 'sunnah',
    inputType: 'boolean',
    cadence: 'monthly:ayyam_beez',
    sortOrder: 310,
    target: null,
    unit: null,
    autoSource: null,
  ),
  (
    key: 'akhlaq_truthful',
    titleBn: 'সর্বদা সত্য কথা বলা',
    titleEn: 'Always Speaking the Truth',
    category: 'akhlaq',
    inputType: 'boolean',
    cadence: 'daily',
    sortOrder: 320,
    target: null,
    unit: null,
    autoSource: null,
  ),
  (
    key: 'akhlaq_anger_control',
    titleBn: 'রাগ নিয়ন্ত্রণ করা',
    titleEn: 'Controlling Anger',
    category: 'akhlaq',
    inputType: 'boolean',
    cadence: 'daily',
    sortOrder: 330,
    target: null,
    unit: null,
    autoSource: null,
  ),
];

/// The bundled catalog as full [AmalDefinition]s, sorted by sortOrder.
List<AmalDefinition> fallbackDefinitions() =>
    kFallbackAmalCatalog
        .map(
          (r) => AmalDefinition(
            key: r.key,
            titleBn: r.titleBn,
            titleEn: r.titleEn,
            category: AmalCategoryJson.fromJson(r.category),
            inputType: switch (r.inputType) {
              'tristate' => AmalInputType.tristate,
              'count' => AmalInputType.count,
              'quantity' => AmalInputType.quantity,
              'text' => AmalInputType.text,
              _ => AmalInputType.boolean,
            },
            cadence: r.cadence,
            target: r.target,
            unit: r.unit,
            minLevel: Level.none,
            sortOrder: r.sortOrder,
            autoSource: r.autoSource,
          ),
        )
        .toList()
      ..sort((a, b) => a.sortOrder.compareTo(b.sortOrder));
