/// Bundled core amal catalog — the offline fallback used by guests and
/// whenever /api/amal/definitions is unreachable. Mirrors the first 15
/// entries (salat_fajr … dua_private_10min) of content/amal-catalog.json
/// EXACTLY (titles, targets, units, sort order) so a guest diary matches
/// the server catalog before the first successful fetch.
library;

import '../models/amal.dart';
import '../models/user.dart';

/// One fallback amal definition (AmalDefinition-shaped record).
/// `target` is the per-user-category target map ({"general":1,"hafez":…}).
typedef FallbackAmal = ({
  String key,
  String titleBn,
  String titleEn,
  String category,
  String inputType,
  String cadence,
  int sortOrder,
  Map<String, num>? target,
  String? unit,
  String? autoSource,
});

const List<FallbackAmal> kFallbackAmalCatalog = <FallbackAmal>[
  (
    key: 'salat_fajr',
    titleBn: 'ফজর নামাজ',
    titleEn: 'Fajr Prayer',
    category: 'salah',
    inputType: 'tristate',
    cadence: 'daily',
    sortOrder: 10,
    target: null,
    unit: null,
    autoSource: 'auto:prayer:fajr',
  ),
  (
    key: 'salat_dhuhr',
    titleBn: 'যোহর নামাজ',
    titleEn: 'Dhuhr Prayer',
    category: 'salah',
    inputType: 'tristate',
    cadence: 'daily',
    sortOrder: 20,
    target: null,
    unit: null,
    autoSource: 'auto:prayer:dhuhr',
  ),
  (
    key: 'salat_asr',
    titleBn: 'আসর নামাজ',
    titleEn: 'Asr Prayer',
    category: 'salah',
    inputType: 'tristate',
    cadence: 'daily',
    sortOrder: 30,
    target: null,
    unit: null,
    autoSource: 'auto:prayer:asr',
  ),
  (
    key: 'salat_maghrib',
    titleBn: 'মাগরিব নামাজ',
    titleEn: 'Maghrib Prayer',
    category: 'salah',
    inputType: 'tristate',
    cadence: 'daily',
    sortOrder: 40,
    target: null,
    unit: null,
    autoSource: 'auto:prayer:maghrib',
  ),
  (
    key: 'salat_isha',
    titleBn: 'ইশা নামাজ',
    titleEn: 'Isha Prayer',
    category: 'salah',
    inputType: 'tristate',
    cadence: 'daily',
    sortOrder: 50,
    target: null,
    unit: null,
    autoSource: 'auto:prayer:isha',
  ),
  (
    key: 'salat_witr',
    titleBn: 'বিতর নামাজ',
    titleEn: 'Witr Prayer',
    category: 'salah',
    inputType: 'boolean',
    cadence: 'daily',
    sortOrder: 60,
    target: null,
    unit: null,
    autoSource: null,
  ),
  (
    key: 'sunnah_muakkadah_12',
    titleBn: '১২ রাকাত সুন্নতে মুয়াক্কাদাহ',
    titleEn: "12 Rak'ah Sunnah Mu'akkadah",
    category: 'salah',
    inputType: 'boolean',
    cadence: 'daily',
    sortOrder: 70,
    target: null,
    unit: null,
    autoSource: null,
  ),
  (
    key: 'tahajjud',
    titleBn: 'তাহাজ্জুদ নামাজ',
    titleEn: 'Tahajjud Prayer',
    category: 'salah',
    inputType: 'boolean',
    cadence: 'daily',
    sortOrder: 80,
    target: null,
    unit: null,
    autoSource: null,
  ),
  (
    key: 'ishraq_salat',
    titleBn: 'ইশরাক নামাজ',
    titleEn: 'Ishraq (Duha) Prayer',
    category: 'salah',
    inputType: 'boolean',
    cadence: 'daily',
    sortOrder: 90,
    target: null,
    unit: null,
    autoSource: null,
  ),
  (
    key: 'tilawat',
    titleBn: 'কুরআন তিলাওয়াত',
    titleEn: "Qur'an Recitation",
    category: 'quran',
    inputType: 'quantity',
    cadence: 'daily',
    sortOrder: 100,
    target: {'general': 1, 'hafez': 1, 'alim': 10},
    unit: 'পৃষ্ঠা/পারা — হাফেজ: ১ পারা · আলেম: ১০ পৃষ্ঠা · সাধারণ: ১ পৃষ্ঠা',
    autoSource: 'auto:quran:tilawat',
  ),
  (
    key: 'quran_reading',
    titleBn: 'কুরআনের অনুবাদ / ইসলামিক গ্রন্থ পাঠ',
    titleEn: "Qur'an Translation / Islamic Reading",
    category: 'quran',
    inputType: 'quantity',
    cadence: 'daily',
    sortOrder: 110,
    target: null,
    unit: 'পৃষ্ঠা',
    autoSource: null,
  ),
  (
    key: 'adhkar_morning',
    titleBn: 'সকালের মাসনূন আযকার (কমপক্ষে ৫ টি)',
    titleEn: 'Morning Adhkar (5 min+)',
    category: 'dhikr',
    inputType: 'boolean',
    cadence: 'daily',
    sortOrder: 120,
    target: null,
    unit: null,
    autoSource: 'auto:adhkar:morning',
  ),
  (
    key: 'adhkar_evening',
    titleBn: 'সন্ধ্যার মাসনূন আযকার (কমপক্ষে ৫ টি)',
    titleEn: 'Evening Adhkar (5 min+)',
    category: 'dhikr',
    inputType: 'boolean',
    cadence: 'daily',
    sortOrder: 130,
    target: null,
    unit: null,
    autoSource: 'auto:adhkar:evening',
  ),
  (
    key: 'post_salat_tasbih',
    titleBn: 'নামাজের পর তাসবীহ ও দোয়া কার্ড',
    titleEn: 'Post-Salah Tasbih & Dua Card',
    category: 'dhikr',
    inputType: 'boolean',
    cadence: 'daily',
    sortOrder: 140,
    target: null,
    unit: null,
    autoSource: 'auto:adhkar:post_salat',
  ),
  (
    key: 'dua_private_10min',
    titleBn: 'কমপক্ষে ১০ মিনিট একান্ত দোয়া/মুনাজাত ও মুহাসাবা',
    titleEn: 'Private Dua & Muhasaba (10 min+)',
    category: 'dhikr',
    inputType: 'boolean',
    cadence: 'daily',
    sortOrder: 150,
    target: null,
    unit: null,
    autoSource: null,
  ),
];

/// The bundled catalog as full [AmalDefinition]s, sorted by sortOrder.
List<AmalDefinition> fallbackDefinitions() => kFallbackAmalCatalog
    .map(
      (r) => AmalDefinition(
        key: r.key,
        titleBn: r.titleBn,
        titleEn: r.titleEn,
        category: AmalCategoryJson.fromJson(r.category),
        inputType: switch (r.inputType) {
          'tristate' => AmalInputType.tristate,
          'count' => AmalInputType.count,
          'quantity' => AmalInputType.quantity,
          'text' => AmalInputType.text,
          _ => AmalInputType.boolean,
        },
        cadence: r.cadence,
        target: r.target,
        unit: r.unit,
        minLevel: Level.none,
        sortOrder: r.sortOrder,
        autoSource: r.autoSource,
      ),
    )
    .toList()
      ..sort((a, b) => a.sortOrder.compareTo(b.sortOrder));
